models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone

class Item(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=1000)
    image = models.FileField()
    # found = models.BooleanField(default=False)
    found_by = models.CharField(max_length=150, blank=True, null=True)
    contact_info = models.CharField(max_length=255)
    creator_username = models.CharField(max_length=150)
    created_at = models.DateTimeField(default=timezone.now) 
    creator_id = models.IntegerField(default=0)
    found_username = models.CharField(max_length=150, blank=True, null=True)
    # creator = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', args=[self.pk])


class Usr(models.Model):
    user_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=255)
    email = models.EmailField()



    def __str__(self):
        return f"{self.user_id}: {self.username}"

class StaffProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='staff_profile')
    department = models.CharField(max_length=100, blank=True, null=True)  # Example field
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    is_staff = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.user.username} - {self.department}"
    
class Profile(models.Model):
    
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
   # image = models.ImageField(default='default.png', upload_to='profile_pics', null=True,  blank=True)
    image = models.FileField(default='default.png', upload_to='profile_pics', null=True, blank=True)

    def str(self):
        return f'{self.user.username} Profile'

forms.py
from django import forms
from .models import Item, Profile
from django.contrib.auth.models import User

class ItemForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter the title'})
    )
    description = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter the description'})
    )
    image = forms.FileField()
    

    class Meta:
        model = Item
        fields = ['title', 'description', 'image', 'contact_info']
        # Add a placeholder for the contact_info field
        widgets = {
            'contact_info': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your contact info'})
        }
        

class ProfileEditForm(forms.ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Enter your username'})
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'placeholder': 'Enter your email'})
    )

    class Meta:
        model = User
        fields = ['username', 'email']
        help_texts = {
            'username': None
        }

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}About Us{% endblock %}
{% block content %}
<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
<style>
    .carousel-item img {
        height: 480px;
        width: auto;
        object-fit: cover;
    }

    p{
        color: white;
    }
    .btn-telegram {
        display: inline-flex;
        align-items: center;
        padding: 10px 20px;
        background-color: #0088cc;
        color: #fff;
        text-decoration: none;
        border-radius: 5px;
        transition: background-color 0.3s ease;
    }
    
    .btn-telegram img {
        margin-right: 10px;
    }
    
    .btn-telegram:hover {
        background-color: #006699;
    }
    .sticky-footer {
        bottom: 0;
        width: 100%;
        background-color: #f8f9fa;
        padding: 20px 0;
        border-top: 1px solid #e7e7e7;
    }

    .footer-container {
        display: flex;
        justify-content: space-around;
        text-align: center;
    }

    .footer-column {
        flex: 1;
        padding: 10px;
    }

    .footer-column h4 {
        color: #333;
        margin-bottom: 10px;
    }

    .footer-column p {
        margin: 0;
    }

    .footer-column h4:nth-child(1) {
        color: #0088cc; /* Color for "Our contacts" */
    }

    .footer-column h4:nth-child(2) {
        color: #28a745; /* Color for "Address" */
    }

    .footer-column h4:nth-child(3) {
        color: #dc3545; /* Color for "Additional" */
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3 text-center">
            <h2 class="mb-4">Lost & Found</h2>
            <p class="lead" style="color: white; font-family: Georgia, 'Times New Roman', Times, serif;">Welcome to Lost & Found. We are dedicated to helping people find lost items and reunite them with their owners.</p>
            <p class="lead" style="color: white; font-family: Georgia, 'Times New Roman', Times, serif;">Our platform allows users to post about lost items, search for lost items, and mark items as found. If you've lost something, don't worry - we're here to help you find it!</p>
            <br>

        </div>
    </div>
</div>
<div class="container my-5">
    <!-- Carousel -->
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'carousel1.jpg' %}" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="{% static 'carousel2.jpg' %}" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="{% static 'carousel3.jpg' %}" class="d-block w-100" alt="...">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <br>
</div>
<script>
    $('.carousel').carousel({
        interval: 2000

    });
</script>
{% endblock content %}

{% block footer %}
<div class="sticky-footer" style="background-color: #003366;" >
    <div class="footer-container" >
        <div class="footer-column" >
            <h4 style="font-family: 'Source Sans Pro', sans-serif; text-transform: uppercase; color: #add8e6">Our contacts</h4>
            <p>            <a href="https://t.me/SDU_Lost_AND_Found" class="btn btn-telegram">
                <img src="{% static 'icon.png' %}" alt="Telegram Icon" style="height: 20px; width: 20px;">
                Lost&Found
            </a></p>
            <p>Site: </p>
            <p>Mail: lostandfound@sdu.edu.kz</p>
        </div>
        <div class="footer-column">
            <h4 style="font-family: 'Source Sans Pro', sans-serif;text-transform: uppercase; color: #add8e6" >Address:  </h4>
            <p>SDU University</p>
            <p>Abylaikhana 1/1</p>

            <p>Almaty, Kaskelen</p>
            <p> Postal : 040900 </p>
        </div>
        <div class="footer-column">
            <h4 style="font-family: 'Source Sans Pro', sans-serif; text-transform: uppercase;color:  #add8e6" >Additional</h4>
            <p>Some additional information goes here.</p>
            <p>Found an error or you have question , contact us ! </p>
        </div>
    </div>
</div>
{% endblock footer %}

templates/base.html
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://use.fontawesome.com/7b81f6ed22.js"></script>
    <title> {% block title %}{% endblock %}</title>
    <style>
        body {
            background-color: #212153;
            color: white;
        }
        .navbar, .footer {
            background-color: #212153;
        }
        .navbar-brand img {
            height: 70px;
            width: 70px;
        }

        .navbar-nav .nav-link {
            font-size: 18px;
        }
        .btn, .form-control, .nav-link, .dropdown-item, .btn-outline-success {
            color: white;
            
        }
        .btn-outline-success {
            
            border-color: white;
        }
        .btn-outline-success:hover {
            background-color: white;
            color: #212153;
        }
        #id_title {
            color: black;
        }
        #id_description {
            
            color: black;
        }

        input[type="file"] {
             display: none;
        
            }
        
        #id_image {
        border: 1px solid #ccc;
        display: inline-block;
        padding: 6px 12px;
        cursor: pointer;

        }
        #id_contact_info{
            color: black;
            width: 70%;
            justify-content:  center;
        }

    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg">
        <a class="navbar-brand" href="/">{% block brand %}<img class="rounded-circle account-img" src="{% static 'sdu.png' %}" style="margin-right: 20px">{% endblock %}</a>
        <a class="navbar-brand" style="color: white;" href="/">Lost & Found </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'view' %}">Lost & Found items</a>
                </li>
                <li class="nav-item {% block about_active %}{% endblock %}">
                    <a class="nav-link" href="{% url 'about_us' %}">About Us</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}" method="get">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            {% if user.is_authenticated %}
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <b>{{ user.username }}</b>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" style="color: black;" href="{% url 'profile' %}">Profile</a>
                    <a class="dropdown-item" style="color: black" href="{% url 'logout' %}">Log out</a>
                </div>
            </div>
            {% else %}
            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'login' %}">Log in</a>
            </div>
            {% endif %}
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    
    {% block footer %}
    <footer class="footer mt-2 py-2">
        <div class="container text-center">
            <p class="mb-0" style="color: white">SDU University, Abylaikhana 1/1, Kaskelen</p>
        </div>
    </footer>
    {% endblock footer %}
</body>
</html>

templates/gallery.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/gal.css' %}">
    <script>
        var gallery = document.querySelector('#gallery');
var getVal = function (elem, style) { return parseInt(window.getComputedStyle(elem).getPropertyValue(style)); };
var getHeight = function (item) { return item.querySelector('.content').getBoundingClientRect().height; };
var resizeAll = function () {
    var altura = getVal(gallery, 'grid-auto-rows');
    var gap = getVal(gallery, 'grid-row-gap');
    gallery.querySelectorAll('.gallery-item').forEach(function (item) {
        var el = item;
        el.style.gridRowEnd = "span " + Math.ceil((getHeight(item) + gap) / (altura + gap));
    });
};
gallery.querySelectorAll('img').forEach(function (item) {
    item.classList.add('byebye');
    if (item.complete) {
        console.log(item.src);
    }
    else {
        item.addEventListener('load', function () {
            var altura = getVal(gallery, 'grid-auto-rows');
            var gap = getVal(gallery, 'grid-row-gap');
            var gitem = item.parentElement.parentElement;
            gitem.style.gridRowEnd = "span " + Math.ceil((getHeight(gitem) + gap) / (altura + gap));
            item.classList.remove('byebye');
        });
    }
});
window.addEventListener('resize', resizeAll);
gallery.querySelectorAll('.gallery-item').forEach(function (item) {
    item.addEventListener('click', function () {        
        item.classList.toggle('full');        
    });
});
    </script>
    <title>Masonry Layout con CSS Grid</title>
</head>
<body>
    <h1>Masonry Gallery</h1>

    <div class="gallery" id="gallery">
        <div class="gallery-item">
            
            <div class="content"><img src="https://source.unsplash.com/random/?tech,care" alt=""></div>
        </div>

        <div class="gallery-item">
            <div class="content"><img src="https://source.unsplash.com/random/?tech,work" alt=""></div>
        </div>


        <div class="gallery-item">
            <div class="content"><img src="https://source.unsplash.com/random/?tech,play" alt=""></div>
        </div>


        <div class="gallery-item">
                <div class="content"><img src="https://source.unsplash.com/random/?tech,play" alt=""></div>

    </div>
   
</div>

    

     
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="jumbotron jumbotron-fluid d-flex flex-column align-items-center justify-content-center" style="background-image: url(//moodle.sdu.edu.kz/pluginfile.php/1/theme_alpha/heroimg/1714460254/0041.jpg); background-size: cover; height: 100vh; background-color: #212153;">
        <div class="text-wrapper d-flex flex-column align-items-center justify-content-center text-center p-4 bg-white shadow-lg animated fadeIn" style="border-radius: 10px;">
            <h1 class="display-4" style="color: #212153; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">Lost & Found</h1>
            <p class="lead" style="color: #212153; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">Helping you find what you've lost and return what you've found.</p>
            <hr class="my-4" style="border-color: #212153;">
            <p style="color: #212153; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">Click below to create a post:</p>
            <img src="{% static 'search.jpg' %}" alt="illus" style="height: 270px; width: 313px; margin-bottom: 20px;">
            <div class="wrap"> <a class="btn btn-primary create-post-btn" href="{% url 'create' %}" role="button">Create Post</a> </div>
        </div>
        {% if error_message %}
            <p class="error-message"><b style="color: red;">{{ error_message }}</b></p>
        {% endif %}
    </div>

    <div class="get-started-section d-flex align-items-center justify-content-between">
        <div class="left-content p-5">
            <h2 class="features-header" style="font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; font-size: 2em;">Put your lost and found things in our  <br> <span class="highlight" style="color: hsl(16, 90%, 37%); text-decoration: underline;">website</span> for free just signing-up! <br> Our website allows to help people find their <span class="highlight" style="color: hsl(16, 90%, 37%); text-decoration: underline;">things </span> easily. <br> Searching , reporting, matching, all in one web-app</h2>
        </div>
        <div class="right-content">
            <img src="{% static 'laptop.png' %}" style="height:450px;width:500px;" alt="Laptop" class="laptop-img">
        </div>
    </div>

    <div style="display: flex; justify-content: center; align-items: center; height: 32vh;">
        <h1 class="features-header" style="font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; font-size: 2em;">Our <span class="highlight" style="color: hsl(16, 90%, 37%);">features,</span><br> that you will get</h1>
    </div>

    <div class="row mt-5">
        <div class="col-md-4">
            <div class="sticker animated bounceIn">
                <img src="{% static 'ic1.png' %}" alt="ic 1" class="img-fluid" style="height: 60px; width: 60px;">
                <h3>It's Secure and Simple</h3>
                <p>Create post to easily find your lost things. Security and simplicity are at the core of our platform, ensuring a smooth and safe experience for all users.</p>
            </div>
        </div>
        <div class="col-md-4">
            <div class="sticker animated bounceIn" style="animation-delay: 0.5s;">
                <img src="{% static 'ic2.png' %}" alt="ic 2" class="img-fluid" style="height: 60px; width: 60px;">
                <h3>Advanced storage</h3>
                <p>Platform will save all data, including contacts to make search easier. All posts are stored in a secure database, ensuring that no information is lost.</p>
            </div>
        </div>
        <div class="col-md-4">
            <div class="sticker animated bounceIn" style="animation-delay: 1s;">
                <img src="{% static 'ic3.png' %}" alt="ic 3" class="img-fluid" style="height: 60px; width: 60px;">
                <h3>Data Protection</h3>
                <p>We implement robust security measures, including encryption and secure servers, to protect your personal information and posted data.</p>
            </div>
        </div>
    </div>
{% endblock %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />

<style>
    .button:hover, .button:focus {
        color: #313133;
        transform: translateY(-6px);
    }

    button:hover::before, button:focus::before {
        opacity: 1;
    }

    button::after {
        content: '';
        width: 30px; height: 30px;
        border-radius: 100%;
        border: 6px solid #00FFCB;
        position: absolute;
        z-index: -1;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        animation: ring 1.5s infinite;
    }

    button:hover::after, button:focus::after {
        animation: none;
        display: none;
    }

    @keyframes ring {
        0% {
            width: 30px;
            height: 30px;
            opacity: 1;
        }
        100% {
            width: 300px;
            height: 300px;
            opacity: 0;
        }
    }

    .create-post-btn {
        animation: bounce 2s infinite;
    }

    .text-wrapper {
        background-color: white;
        padding: 20px;
        border-radius: 10px;
    }

    .text-wrapper h1, .text-wrapper p, .text-wrapper a {
        color: #212153;
        font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    }

    .jumbotron {
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .sticker {
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .sticker img {
        max-width: 100%;
        height: auto;
    }

    .get-started-section {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .left-content {
        flex: 1;
    }

    .right-content {
        flex: 1;
        display: flex;
        justify-content: flex-end;
    }

    .laptop-img {
        height: 450px;
        width: 500px;
    }
</style>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        console.log("Page loaded, starting animation");
        var btn = document.querySelector('.create-post-btn');
        btn.classList.add('animated', 'fadeIn');

        // Carousel initialization
        $('.carousel').carousel({
            interval: 2000
        });
    });
</script>

templates/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block home_active %}active{% endblock %}
{% block content %}

<style>
    .card {
    transition: transform .2s; /* Animation */
}
.card-img-top {
    width: 100%;
    height: 200px;
    object-fit: contain;
    background-color: #f8f8f8;
}
.card:hover {
    transform: scale(1.05); 
}
.username {
    color: #000000;
}
</style>

    <div class="container">
        <div class="row">
        {% for i in items %}
            <div class="card col-12 col-sm-6 col-md-4 mb-3">
              <img class="card-img-top" src="{{ i.image.url }}" alt="{{ i.title }}">
              <div class="card-body">
                <h5 class="card-title"  style="color: black;">{{ i.title }}</h5>
                <p class="card-text"  style="color: black;">{{ i.description }}</p>

                <p class="card-text" style="color:black"><b style="color: black;">Contact:</b> {{ i.contact_info }}</p>
                <p class="card-text"><b  style="color: black;">@{{ i.creator_username }}</b></p>
                <p class="card-text"><b  style="color: black;">{{ i.created_at }}</b></p>
                {% if i.found_by %}
                    <h5 class="text-success">Found by <span class="username"> @{{i.found_username}} </span> </h5>
                
                {% else %}
                    <h5 class="text-danger">Not Found</h5>
                    <form method="post" action="{% url 'found' %}">
                        {% csrf_token %}
                        <input type="hidden" name="item" value="{{ i.pk }}"/>
                        <button type="submit" class="btn btn-success btn-block">Found it!</button>
                    </form>
                {% endif %}
              </div>
{#              {% if request.user.username == i.creator_username %}#}
                  <div class="card-footer">
                      <a href="{{ i.get_absolute_url }}" class="btn btn-outline-primary btn-block" style="color: black;">Read more</a>
                  </div>
{#              {% endif %}#}
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

templates/item.html
{% extends 'base.html' %}
{% block title %}{{ item.title }}{% endblock %}
{% block content %}
    <img class="img-rounded img-responsive" src="{{ item.image.url }}" />
    <h1>{{ item.title }}</h1>
    <p class="lead">{{ item.description }}</p>

    {% if request.user.username == item.creator_username or request.user.is_staff %}
    <a href="{% url 'edit' item.pk %}" class="btn btn-warning"><span class="fa fa-edit"></span></a>
    <a href="{% url 'delete' item.pk %}" class="btn btn-danger"><span class="fa fa-remove"></span></a>
    {% endif %}

{% endblock %}

templates/item_delete.html
{% extends 'base.html' %}
{% block title %}Delete item{% endblock %}
{% block content %}
<style>
    .centered-form {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        width: 300px;
        padding: 20px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    
    .animated {
        animation-duration: 1s;
        animation-fill-mode: both;
    }
    
    @keyframes fadeIn {
        0% {opacity: 0;}
        100% {opacity: 1;}
    }
    
    .fadeIn {
        animation-name: fadeIn;
    }
    </style>

<div class="centered-form animated fadeIn">
    <form method="post">
        {% csrf_token %}
        <p style="color: black;">Are you sure?</p>
        <button type="submit" class="btn btn-danger">Yes</button>
        <a href="{% url 'index' %}" class="btn btn-success">No</a>
    </form>
</div>
{% endblock %}

templates/item_form.html
{% extends 'base.html' %}
{% block title %}Create Item{% endblock %}
{% block create_active %}active{% endblock %}
{% block content %}
    <h1>Create a new Item</h1>
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
            <label >{{field.label_tag}}</label>
             {{field}}
            <span style="color: red;">{{field.error}}</span>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">OK</button>
    </form>
{% endblock %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            font-family: Arial, sans-serif;
            background-color: #e9ecef;
        }
        .container {
            display: flex;
            width: 80%;
            max-width: 1200px;
            background-color: #fff;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
            border-radius: 8px;
            overflow: hidden;
        }
        .left {
            flex: 1;
            padding: 40px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            background-color: #fff;
            margin-right: 40px;
        }
        .left img {
            width: 150px;
            margin-bottom: 20px;
        }
        .left h2 {
            margin-bottom: 20px;
            color: #333;
        }
        .left p {
            margin-bottom: 20px;
            color: #666;
        }
        .left label {
            align-self: flex-start;
            color: #333;
            margin-bottom: 5px;
        }
        .left input {
            width: 100%;
            padding: 10px;
            margin: 10px 0;
            border: 1px solid #ddd;
            border-radius: 4px;
        }
        .left button {
            width: 100%;
            padding: 10px;
            border: none;
            background-color: #007bff;
            color: #fff;
            font-size: 16px;
            border-radius: 20px;
            cursor: pointer;
            margin-top: 20px;
        }
        .left button:hover {
            background-color: #0056b3;
            color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
        }
        .left a {
            color: #007bff;
            margin-top: 10px;
            text-decoration: none;
        }
        .left a:hover {
            text-decoration: underline;
        }
        .right {
            flex: 1;
            background: url('{% static "image.png" %}') no-repeat center center/cover;
        }
        .footer {
            display: flex;
            justify-content: center;
            margin-top: 20px;
        }
        .footer a {
            margin: 0 10px;
            text-decoration: none;
            color: #007bff;
        }
        .footer a:hover {
            text-decoration: underline;
        }
        .error-message {
            color: red;
            margin-top: 10px;
            transition: opacity 1s ease-out;

        }
    </style>
    <script>
        window.onload = function() {
            var errorMessage = document.querySelector('.error-message');
            if (errorMessage) {
                setTimeout(function() {
                    errorMessage.style.opacity = '0';
                }, 4000); 
            }
        };
    </script>
</head>
<body>
    {% block content %}
    {% if user.is_authenticated %}
        <p>You are logged in as {{ user.username }}.</p>
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <div class="container">
            <div class="left">
                <img src="{% static 'your-logo.svg' %}" alt="Logo" style="height: 200px; width: 200px;">
                <h2>Sign in</h2>
                <p>Welcome back, please sign in to your account.</p>
                <form method="POST">
                    {% csrf_token %}
                    <label for="id_username">Username:</label>
                    <input type="text" name="username" id="username" placeholder="Username" required>
                    <label for="id_password">Password:</label>
                    <input type="password" id="password" name="password" placeholder="Password" required>
                    <button type="submit">Continue</button>
                    {% if error_message %}
                        <p class="error-message"><b style="color: red;">{{ error_message }}</b></p>
                    {% endif %}
                </form>
                <a href="{% url 'registration' %}">Not registered yet?</a>
            </div>
            <div class="right">
                <div style="display: flex; flex-direction: column; justify-content: center; align-items: center; height: 100vh;">
                    <h1>Lost and Found site</h1>
                    <div class="lowtext">
                        L&F community is designed to help students and notify about lost things. To post a notification please sign up.
                    </div>
                </div>
            </div>
        </div>
        <!-- <div class="footer">
            <a href="#">Privacy Policy</a>
            <a href="#">Terms of Service</a>
            <a href="#">Support</a>
        </div> -->
    {% endif %}
    {% endblock %}
</body>
</html>